/**
 * Message catalog for the MARCOM pages. The app has no i18n framework yet (English only, no RTL),
 * so every user-visible string lives here behind t() -- when a translation mechanism arrives, this
 * is the single file to feed it. Keys are flat and stable; {placeholders} are filled by t().
 */
const EN = {
  // pages
  'page.spending': 'MARCOM Spending',
  'page.campaigns': 'Media Campaign Performance',
  'page.digital': 'Digital Performance',
  'page.trade': 'Trade Marketing & Retail',
  // header / freshness
  'freshness.line': 'Data as of {period} — uploaded by {user} on {date}',
  'freshness.unknownUser': 'unknown',
  'header.upload': 'Upload data',
  // filters
  'filter.year': 'Year',
  'filter.from': 'From',
  'filter.to': 'To',
  'filter.brand': 'Brand',
  'filter.platform': 'Platform',
  'filter.status': 'Campaign status',
  'filter.all': 'All',
  'filter.selected': '{n} selected',
  'filter.reset': 'Reset',
  'filter.bar': 'Filters',
  'filter.refreshing': 'Updating…',
  // states
  'state.loading': 'Loading…',
  'state.empty': 'No data for the selected filters',
  'state.emptyHint': 'Try a different period, brand or platform.',
  'state.noData': 'No MARCOM data uploaded yet',
  'state.noDataHint': 'Once the Marketing Director’s workbook has been uploaded, this page fills in.',
  'state.noDataAdmin': 'Go to MARCOM Data Upload',
  'state.error': 'This page could not load.',
  'state.chartError': 'This chart could not load.',
  'state.retry': 'Retry',
  'state.noAccess': 'You do not have access to this page',
  'state.noAccessHint': 'Ask an administrator to grant you View permission for it.',
  'state.noLastYear': 'No last-year data uploaded',
  'state.noLastYearHint': 'Upload last year’s months to see the comparison.',
  // chart card
  'chart.viewTable': 'View as table',
  'chart.viewChart': 'View as chart',
  'chart.updating': 'Updating',
  // RAG
  'rag.green': 'On target',
  'rag.yellow': 'Watch',
  'rag.red': 'Off target',
  'rag.neutral': 'No target',
  'rag.na': 'n/a',
  'rag.naReason': 'Not available: there is no data, or a zero denominator, for the selected period.',
  'rag.legend.green': 'On target',
  'rag.legend.yellow': 'Watch',
  'rag.legend.red': 'Off target',
  // delta
  'delta.better': 'improving',
  'delta.worse': 'worsening',
  'delta.flat': 'unchanged',
  'delta.vsPrevious': 'vs previous',
  // units / generic
  'unit.lyd': 'LYD',
  'unit.percent': '%',
  'unit.min': 'min',
  'unit.units': 'units',
  'generic.month': 'Month',
  'generic.brand': 'Brand',
  'generic.platform': 'Platform',
  'generic.status': 'Status',
  'generic.total': 'Total',
  'generic.value': 'Value',
  'generic.na': 'n/a',
  'generic.asOf': 'as of {period}',
  'generic.asOfHeader': 'As of',
  'generic.overBudget': 'Over budget',
  'generic.overdue': 'Overdue',
  'generic.today': 'Today',
  'generic.planned': 'Planned',
  'generic.completed': 'Completed',
  // page 1
  'p1.spendVsRevenue': 'Total Spend vs Total Revenue',
  'p1.spend': 'Total Spend',
  'p1.revenue': 'Revenue Attributed to Marketing',
  'p1.companyRevenue': 'Total Company Revenue',
  'p1.showCompany': 'Overlay company revenue',
  'p1.roiTrend': 'ROI trend — YTD vs LYTD',
  'p1.roiYtd': 'ROI (YTD)',
  'p1.roiLytd': 'LYTD',
  'p1.roiCurrent': 'This year',
  'p1.roiLastYear': 'Last year',
  'p1.roiBandGreen': 'Green above 1 : {v}',
  'p1.roiBandRed': 'Red below 1 : {v}',
  'p1.budget': 'Budget utilization by brand',
  'p1.budgetLine': '100% of budget',
  'p1.budgetTip': '{spent} spent of {budget}',
  'p1.growth': 'Brand growth',
  'p1.growthTip': 'Current {cur} · last year {ly}',
  'p1.cac': 'CAC — Customer Acquisition Cost',
  'p1.cacPct': '{v} of average invoice',
  'p1.cacInvoice': 'CAC % of invoice',
  'p1.cpc': 'CPC — Cost per Click',
  'p1.cpcPerBrand': 'CPC by brand',
  // page 2
  'p2.spendVsRevenue': 'Spend vs Revenue by Campaign',
  'p2.rate': 'Total Spend vs Revenue Rate',
  'p2.rateNote': 'Revenue ÷ Spend',
  'p2.totalSpend': 'Total spend',
  'p2.totalRevenue': 'Total revenue',
  'p2.roiByCampaign': 'ROI by Campaign',
  'p2.roiLegendGreen': 'Above 1 : {v}',
  'p2.roiLegendYellow': '1 : {lo} to 1 : {hi}',
  'p2.roiLegendRed': 'Below 1 : {v}',
  'p2.roiNa': 'ROI not available for: {names}',
  'p2.timeline': 'Campaign timeline',
  'p2.coverage': 'Geographic coverage by type',
  'p2.coverageCentre': 'units',
  'p2.cost': 'Cost by type',
  'p2.costBars': 'Bars',
  'p2.costBubbles': 'Bubbles',
  'p2.costUnits': 'Units',
  'p2.costPerUnit': 'Cost per unit',
  // page 3
  'p3.followers': 'Followers / Likes by platform',
  'p3.metaTotal': 'Meta total (Facebook + Instagram): {v}',
  'p3.ctr': 'CTR — Click-through rate',
  'p3.engagement': 'Engagement Rate',
  'p3.overall': 'Overall',
  'p3.organicVsPaid': 'Organic vs Paid engagement per month',
  'p3.paid': 'Paid',
  'p3.organic': 'Organic',
  'p3.organicShare': 'Organic share',
  'p3.stacked': 'Stacked',
  'p3.grouped': 'Grouped',
  'p3.bounce': 'Bounce Rate',
  'p3.bounceNote': 'Lower is better',
  'p3.session': 'Average Session Duration',
  // page 4
  'p4.compliance': 'Compliance Rate',
  'p4.giveaways': 'Giveaways Stock',
  'p4.printed': 'Printed Materials Stock',
  'p4.average': 'Average for the period: {v}',
  'p4.latest': 'Latest month: {period}',
  'p4.eventsByType': 'Events by type — per month',
  'p4.includePlanned': 'Include planned',
  'p4.completedOnly': 'Completed only',
  'p4.cancelledNote': 'Cancelled events are excluded.',
  'p4.eventsTimeline': 'Events timeline — plan vs completion',
  'p4.viewGantt': 'Timeline',
  'p4.viewTable': 'Table',
  'p4.summaryPlanned': 'Planned',
  'p4.summaryCompleted': 'Completed',
  'p4.summaryPct': 'Completion',
  'p4.attendance': 'Attendance Rate',
  'p4.actual': 'Actual',
  'p4.expected': 'Expected',
  'p4.event': 'Event',
  'p4.type': 'Type',
  'p4.plannedDate': 'Planned',
  'p4.completionDate': 'Completion',
  // gantt
  'gantt.label': 'Timeline chart',
  'gantt.legend': 'Legend',
  'gantt.showAll': 'Show all {n}',
  'gantt.clippedStart': 'Starts before the selected period',
  'gantt.clippedEnd': 'Ends after the selected period',
  'gantt.milestone': 'Milestone',
  'gantt.noRows': 'Nothing to show on the timeline',
  'gantt.from': 'From',
  'gantt.to': 'To',
  'gantt.duration': 'Duration',
  'gantt.days': '{n} days',
  'gantt.brand': 'Brand',
  'gantt.spend': 'Spend',
  'gantt.revenue': 'Revenue',
  'gantt.roi': 'ROI',
  'gantt.planned': 'Planned',
  'gantt.completion': 'Completion',
  'gantt.notCompleted': 'not completed',
} as const;

export type TextKey = keyof typeof EN;

export function t(key: TextKey, params?: Record<string, string | number>): string {
  let s: string = EN[key] ?? key;
  if (params) for (const [k, v] of Object.entries(params)) s = s.split(`{${k}}`).join(String(v));
  return s;
}

/** Status keys for campaign / event lifecycle labels (data values, shown as-is). */
export const STATUS_LABEL_PREFIX = 'status.';
