/**
 * Kaizen module text -- English only (the module deliberately ignores the app's language switch).
 * `kaizen.*` = UI strings; `err.*` = messages for backend validation codes
 * (backend/src/services/kaizenService.ts's KaizenValidationError).
 */
export const KAIZEN_TEXT = {
  'kaizen.board': 'Kaizen Board',
  'kaizen.loading': 'Loading...',
  'kaizen.cardsTitle': 'Kaizen Cards',
  'kaizen.detailsTitle': 'Kaizen Card Details',
  'kaizen.manageTitle': 'Manage Kaizen Cards',
  'kaizen.dropdownsTitle': 'Kaizen Dropdown Values',
  'kaizen.newCard': 'Add card',
  'kaizen.editCard': 'Edit card #{no}',
  'kaizen.viewCard': 'Card #{no}',
  'kaizen.manageLink': 'Manage cards',
  'kaizen.detailsLink': 'Card details',
  'kaizen.backToBoard': 'Kaizen Board',
  'kaizen.f.no': 'No',
  'kaizen.f.creator': 'Card Creator / Submitter',
  'kaizen.f.date': 'Date',
  'kaizen.f.department': 'Department',
  'kaizen.f.cardName': 'Card Name',
  'kaizen.f.type': 'Card Type',
  'kaizen.f.issue': 'Issue',
  'kaizen.f.rootCause': 'Root Cause',
  'kaizen.f.impact': 'Impact',
  'kaizen.f.priority': 'Card Priority',
  'kaizen.f.solution': 'Proposed Solution',
  'kaizen.f.expectedDate': 'Expected Date',
  'kaizen.f.closerDate': 'Closer Date',
  'kaizen.f.responsible': 'Responsible Party',
  'kaizen.f.status': 'Status',
  'kaizen.f.createdBy': 'Entered by',
  'kaizen.f.updatedBy': 'Last updated by',
  'kaizen.required': 'required',
  'kaizen.optional': 'optional',
  'kaizen.status.OPEN': 'Open',
  'kaizen.status.CLOSED': 'Closed',
  'kaizen.notAssigned': '(Not assigned)',
  'kaizen.overdue': 'Overdue',
  'kaizen.overdueHint': 'Open and past its Expected Date',
  'kaizen.inactive': 'inactive',
  'kaizen.filter.from': 'From',
  'kaizen.filter.to': 'To',
  'kaizen.filter.allDepartments': 'All departments',
  'kaizen.filter.all': 'All',
  'kaizen.filter.search': 'Search name, issue, person or #',
  'kaizen.filter.overdueOnly': 'Overdue only',
  'kaizen.filter.reset': 'Reset filters',
  'kaizen.filter.active': 'Filtered by: {what}',
  'kaizen.filter.creator': 'Submitter',
  'kaizen.list.count': '{n} cards',
  'kaizen.list.empty': 'No cards match these filters.',
  'kaizen.list.newestFirst': 'Newest first',
  'kaizen.list.tapHint': 'Tap a card to see all its details.',
  'kaizen.actions': 'Actions',
  'kaizen.edit': 'Edit',
  'kaizen.close': 'Close card',
  'kaizen.delete': 'Delete',
  'kaizen.view': 'View',
  'kaizen.export': 'Export to Excel',
  'kaizen.exporting': 'Exporting…',
  'kaizen.import': 'Import from Excel (one-time)',
  'kaizen.confirmDelete': 'Delete card #{no} "{name}"? It disappears from the board and lists; its number is never reused.',
  'kaizen.save': 'Save',
  'kaizen.saving': 'Saving…',
  'kaizen.cancel': 'Cancel',
  'kaizen.choose': 'Choose…',
  'kaizen.saved': 'Card saved.',
  'kaizen.closeDialogTitle': 'Close card #{no}',
  'kaizen.closeDialogText': 'The card will be marked Closed with this Closer Date.',
  'kaizen.confirmClose': 'Close card',
  'kaizen.closerHint': 'Required when Status is Closed.',
  'kaizen.responsibleHint': 'Pick a previous name to keep spelling consistent.',
  'kaizen.readOnly': 'Read-only view',
  'kaizen.notFound': 'Card not found.',
  'kaizen.loadError': 'Could not load Kaizen data.',
  'kaizen.kpi.total': 'Total cards',
  'kaizen.kpi.avgDays': 'Avg. days to close',
  'kaizen.kpi.topDepartment': 'Top department',
  'kaizen.kpi.topSubmitter': 'Top submitter',
  'kaizen.kpi.topCause': 'Top cause',
  'kaizen.kpi.details': 'See the details',
  'kaizen.unit.cards': 'cards',
  'kaizen.unit.days': 'days',
  'kaizen.kpi.avgHint': 'Average of (Closer Date − Date) over Closed cards',
  'kaizen.chart.byDepartment': 'Cards per department',
  'kaizen.chart.priority': 'Card priority',
  'kaizen.chart.status': 'Card status',
  'kaizen.chart.type': 'Card type',
  'kaizen.chart.responsible': 'Cards by Responsible Party',
  'kaizen.chart.others': 'Others',
  'kaizen.chart.othersHint': 'Every responsible party outside the top 10, combined.',
  'kaizen.chart.responsibleHint': 'Top 10 by number of cards, split into Open and Closed. Click a bar to open its cards.',
  'kaizen.chart.clickHint': 'Click a segment to open the matching cards.',
  'kaizen.chart.noData': 'No cards in this period.',
  'kaizen.qr.download': 'Download QR (PNG)',
  'kaizen.qr.scan': 'Scan to open the card details',
  'kaizen.cardsWord': 'Cards',
  'kaizen.dd.list.department': 'Department',
  'kaizen.dd.list.card_type': 'Card Type',
  'kaizen.dd.list.card_priority': 'Card Priority',
  'kaizen.dd.label': 'Label',
  'kaizen.dd.color': 'Colour',
  'kaizen.dd.order': 'Order',
  'kaizen.dd.active': 'Active',
  'kaizen.dd.inactive': 'Inactive',
  'kaizen.dd.usage': 'Used by',
  'kaizen.dd.add': 'Add value',
  'kaizen.dd.deactivate': 'Deactivate',
  'kaizen.dd.reactivate': 'Reactivate',
  'kaizen.dd.moveUp': 'Move up',
  'kaizen.dd.moveDown': 'Move down',
  'kaizen.dd.note': 'Deactivated values disappear from the entry form, but cards that already use them keep them and the dashboard still counts them. A value used by any card cannot be deleted, only deactivated.',
  'kaizen.dd.confirmDelete': 'Delete "{label}" permanently?',
  'kaizen.imp.title': 'One-time import of existing cards',
  'kaizen.imp.help': 'Upload the existing Kaizen cards (.xlsx). Columns are matched by name. Department, Card Type and Card Priority must match an existing value; unknown text is reported, never created. A "No" column keeps the numbers written on the board.',
  'kaizen.imp.check': 'Check file',
  'kaizen.imp.commit': 'Import {n} cards',
  'kaizen.imp.rows': '{valid} of {total} rows are valid.',
  'kaizen.imp.row': 'Row {row}',
  'kaizen.imp.done': '{n} cards imported.',
  'kaizen.imp.already': 'Cards were already imported once. Delete the imported cards to import again.',
  'kaizen.imp.unmatched': 'Values with no match (add them in Dropdown Values first if they are real):',
  'err.card.creatorRequired': 'Card Creator is required.',
  'err.card.creatorLength': 'Card Creator is limited to 150 characters.',
  'err.card.dateRequired': 'Date is required.',
  'err.card.dateInvalid': 'Date is not a valid date.',
  'err.card.nameRequired': 'Card Name is required.',
  'err.card.nameLength': 'Card Name is limited to 200 characters.',
  'err.card.departmentRequired': 'Department is required.',
  'err.card.typeRequired': 'Card Type is required.',
  'err.card.priorityRequired': 'Card Priority is required.',
  'err.card.issueRequired': 'Issue is required.',
  'err.card.expectedInvalid': 'Expected Date is not a valid date.',
  'err.card.expectedBeforeDate': 'Expected Date cannot be before the card Date.',
  'err.card.statusInvalid': 'Status must be Open or Closed.',
  'err.card.closerInvalid': 'Closer Date is not a valid date.',
  'err.card.closerRequired': 'Closer Date is required when the card is Closed.',
  'err.card.closerOnlyWhenClosed': 'Closer Date must be empty while the card is Open.',
  'err.card.closerBeforeDate': 'Closer Date cannot be before the card Date.',
  'err.card.responsibleLength': 'Responsible Party is limited to 150 characters.',
  'err.card.valueInactive': 'The selected value is no longer active.',
  'err.card.departmentInvalid': 'Choose a valid Department.',
  'err.card.typeInvalid': 'Choose a valid Card Type.',
  'err.card.priorityInvalid': 'Choose a valid Card Priority.',
  'err.card.notFound': 'Card not found.',
  'err.dropdown.label': 'Label is required.',
  'err.dropdown.color': 'Colour must be a hex value like #4d88c4.',
  'err.dropdown.duplicate': 'This label already exists in the list.',
  'err.dropdown.inUse': 'This value is used by cards and can only be deactivated.',
  'err.generic': 'Something went wrong. Please try again.',
};

export type KaizenTextKey = keyof typeof KAIZEN_TEXT;

/** Kaizen text for `key`; `{name}` placeholders are filled from `vars`. */
export function kt(key: KaizenTextKey, vars?: Record<string, string | number>): string {
  let text: string = KAIZEN_TEXT[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) text = text.split(`{${k}}`).join(String(v));
  return text;
}

/** The message for a backend error code, or null when there is no specific one. */
export function errorText(code: string | null | undefined): string | null {
  const key = `err.${code}`;
  return code && key in KAIZEN_TEXT ? KAIZEN_TEXT[key as KaizenTextKey] : null;
}

/** Numbers with thousands separators and at most `digits` decimals. */
export function formatNumber(value: number, digits = 0): string {
  return value.toLocaleString('en-US', { maximumFractionDigits: digits });
}
